export const FETCH_CONFIGURATION = 'FETCH_CONFIGURATION';
export const FETCH_CONFIGURATION_SUCCESS = 'FETCH_CONFIGURATION_SUCCESS';
export const FETCH_CONFIGURATION_FAIL = 'FETCH_CONFIGURATION_FAIL';

export const CHANGE_SELECTED_BAR = 'CHANGE_SELECTED_BAR';
export const CHANGE_BAR_VALUE = 'CHANGE_BAR_VALUE';
